Sm/fix-no-unused
salesforcecli/sf-plugins-core pull request #41
Opened 2022-03-16 14:33 UTC by mshanemc

@W-10749241@ 

simplified confirm on Prompter
update logic for "is it a devHub"
fix logic error on timedPrompt ms being unused
require higher oclif/core so ux.stylizedHeader tests don't fail

2022-03-16 14:56 UTC, peternhale requested changes

2022-03-16 14:56 UTC, peternhale commented on src/sfCommand.ts
> +    return this.prompter.timedPrompt(questions, ms, initialAnswers);
Fixed in HEAD

2022-03-16 14:56 UTC, peternhale commented on src/sfCommand.ts
> +    const { confirmed } = await this.prompt<{ confirmed: boolean }>([
``` suggestion
    const { confirmed } = await this.timedPrompt<{ confirmed: boolean }>([
```

2022-03-16 14:56 UTC, peternhale commented on src/sfCommand.ts
> +    const { confirmed } = await this.prompt<{ confirmed: boolean }>([
I would also consider adding timeout value and default to 10s.

2022-03-16 17:59 UTC, RodEsp approved these changes

2022-03-17 13:27 UTC, peternhale approved these changes

2022-03-17 16:01 UTC, merged