fix: docs about required flags that read from config
salesforcecli/sf-plugins-core pull request #455
Opened 2023-11-17 15:43 UTC by mshanemc

flag summary change

@W-14512755@
https://github.com/forcedotcom/cli/issues/2538

2023-11-17 16:28 UTC, shetzel approved these changes

2023-11-20 22:13 UTC, jshackell-sfdc requested changes
Tweaked the wording -- okay?

2023-11-20 22:13 UTC, jshackell-sfdc commented on messages/messages.md
> +Username or alias of the target org. Can be omitted if `target-org` exists in the config.
```suggestion
Username or alias of the target org. Not required if the `target-org` configuration variable is already set.
```

2023-11-20 22:13 UTC, jshackell-sfdc commented on messages/messages.md
> +Username or alias of the Dev Hub org. Can be omitted if `target-dev-hub` exists in the config.
```suggestion
Username or alias of the Dev Hub org. Not required if the `target-dev-hub` configuration variable is already set.
```

2023-11-21 19:47 UTC, merged