feat!: use current inquirer
salesforcecli/sf-plugins-core pull request #479
Opened 2024-01-03 15:08 UTC by mshanemc

BREAKING CHANGE: ESM-only

BREAKING CHANGE: removes cross-cloud hooks (deployer, deauthorizer, etc)

BREAKING CHANGE: removes Prompter module

BREAKING CHANGE: remove option to barrel-import from Ux

2024-01-03 20:01 UTC, mdonnalley approved these changes
Changes look good to me 👍 

Looks like you have some merge conflicts though. Also, I'm assuming that the failing nuts are expected?

2024-01-03 20:01 UTC, mdonnalley commented on README.md
> +## Prompts
Do you want to add some content here?

2024-01-03 20:37 UTC, mdonnalley commented
### QA

Generated new sf plugin using `sf dev generate plugin`, linked this branch of sf-plugins-core to it.

🟢 `this.confirm` prompts user for `Y/n` answer
🟢 `this.confirm` defaults to `defaultAnswer` after 10 second timeout
❌  `this.confirm` hangs until timeout despite being answered

🟢  `this.secretPrompt` prompts user and input is hidden
❌  `this.secretPrompt` hangs until timeout despite being answered

2024-01-04 16:05 UTC, mdonnalley commented
QA
Generated new sf plugin using sf dev generate plugin, linked this branch of sf-plugins-core to it.

🟢 `this.confirm` prompts user for Y/n answer
🟢 `this.confirm` defaults to defaultAnswer after 10 second timeout
🟢 `this.confirm` cancels timeout if answer is given

🟢 `this.secretPrompt` prompts user and input is hidden
🟢 `this.secretPrompt` cancels timeout if answer is given

2024-01-04 17:57 UTC, mshanemc commented
> Changes look good to me 👍
> 
> Looks like you have some merge conflicts though. Also, I'm assuming that the failing nuts are expected?

PDR needs https://github.com/salesforcecli/plugin-deploy-retrieve/pull/866 to even compile without the `Deployer` hook stuff.

The other 2 (org and signups) are expected results of the breaking changes in here.

2024-01-05 19:40 UTC, mdonnalley requested changes

2024-01-05 19:40 UTC, mdonnalley commented on MIGRATING_V5-V6.md
> +1. plugins that need more advanced propting should import the parts of inquirer that they need
`2.`

2024-01-05 19:40 UTC, mdonnalley commented on MIGRATING_V5-V6.md
> +The `Prompter`` class is removed.
There's an extra tick at the end of `Prompter`

2024-01-05 19:40 UTC, mdonnalley commented on MIGRATING_V5-V6.md
> +1. `secretPrompt` takes masked string input from the user
`2.`

2024-01-05 19:40 UTC, mdonnalley commented on MIGRATING_V5-V6.md
> +Unlike then inquirer base prompts (`confirm` and `password`, respectively) these have a built-in default timeout. Both take an object parameter that lets you change the timeout (confirm previously to
`Unlike the`

2024-01-05 21:25 UTC, mdonnalley approved these changes

2024-01-05 21:53 UTC, merged